---
name: 🚀 Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildandrelease:
    runs-on: ubuntu-latest
    name: 🚀 Build and Release
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0

      - name: 🔎 Get app_name from manifest.json
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58
        id: app_name
        with:
          cmd: 'jq .name src/manifest.json -r'

      - name: min app_name
        id: min_app_name
        run: |
          min_app_name=$(echo ${{steps.app_name.outputs.value}} | tr " " "-" | tr '[:upper:]' '[:lower:]')
          echo "min_app_name=${min_app_name}" >> $GITHUB_OUTPUT

      - name: 🔎 Get app_version from manifest.json
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58
        id: app_version
        with:
          cmd: 'jq .version src/manifest.json -r'

      - name: Copy to build
        run: |
          mkdir ./build
          rsync -r ./src/* ./build

      - name: Minify
        uses: devatherock/minify-js@c4f40af50c45f8727c1a404d65f8dac342247b81
        with:
          directory: 'build'
          add_suffix: false

      - name: 📦 Archive Release
        uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
        with:
          directory: './build'
          type: 'zip'
          filename: '${{steps.min_app_name.outputs.min_app_name}}_${{steps.app_version.outputs.value}}.zip'
          exclusions: '*.git*'

      - name: 🚀 Upload Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          artifacts: "./build/${{steps.min_app_name.outputs.min_app_name}}_${{steps.app_version.outputs.value}}.zip"
          tag: "${{steps.app_version.outputs.value}}"
          body: "${{steps.app_name.outputs.value}} version ${{steps.app_version.outputs.value}}"
          token: ${{ secrets.GITHUB_TOKEN }}
